version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR.... 
      - aws --version
      - $(aws ecr get-login --no-include-email --region us-east-1)
      # Get commit hash value to tag the image
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      # Replace with your application name
      - APPLICATION_NAME=auto-escola
      # Replace with this 435320931996.dkr.ecr.ap-south-1.amazonaws.com to your repository URI
      - REPOSITORY_URI=593047862826.dkr.ecr.us-east-1.amazonaws.com/auto-escola/$APPLICATION_NAME
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"order-service","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
   - imagedefinitions.json
   - target/order-service.jar

